### PR TITLE
add image resource

### PR DESCRIPTION
**Pull request by dbasunag**

### CODE REVIEW

**Comment by dbasunag** [comment]
!verified

**Review by myakove — APPROVED** [review]

**Comment by dbasunag** [comment]
!cherry-pick v-4.11

**Comment by dbasunag** [comment]
!cherry-pick v4.11

**Comment by myakove** [comment]
!cherry-pick v-4.11

**Comment by myakove** [comment]
!cherry-pick v-4.11

**Comment by dbasunag** [comment]
!cherry-pick v4.11

**Comment by myakove** [comment]
!cherry-pick v4.11

**Comment by myakove** [comment]
!cherry-pick v-4.11

**Pull request merged**
