### PR TITLE
Move `resources-definitions` update script to this repository

### PR DESCRIPTION
**Pull request by myakove**
Move update resources definitions script from https://github.com/RedHatQE/openshift-resources-definitions

### CODE REVIEW

**Comment by redhat-qe-bot1** [comment]
Report bugs in [Issues](https://github.com/myakove/github-webhook-server/issues)

The following are automatically added:
 * Add reviewers from OWNER file (in the root of the repository) under reviewers section.
 * Set PR size label.
 * New issue is created for the PR. (Closed when PR is merged/closed)
 * Run [pre-commit](https://pre-commit.ci/) if `.pre-commit-config.yaml` exists in the repo.

Available user actions:
 * To mark PR as WIP comment `/wip` to the PR, To remove it from the PR comment `/wip cancel` to the PR.
 * To block merging of PR comment `/hold`, To un-block merging of PR comment `/hold cancel`.
 * To mark PR as verified comment `/verified` to the PR, to un-verify comment `/verified cancel` to the PR.
        verified label removed on each new commit push.
 * To cherry pick a merged PR comment `/cherry-pick <target branch to cherry-pick to>` in the PR.
    * Multiple target branches can be cherry-picked, separated by spaces. (`/cherry-pick branch1 branch2`)
    * Cherry-pick will be started when PR is merged
 * To build and push container image command `/build-and-push-container` in the PR (tag will be the PR number).
 * To add a label by comment use `/<label name>`, to remove, use `/<label name> cancel`

<details>
<summary>Supported /retest check runs</summary>

 * `/retest tox`: Retest tox
 * `/retest python-module-install`: Retest python-module-install

</details>

<details>
<summary>Supported labels</summary>

 * hold
 * verified
 * wip
 * lgtm

</details>

**Review by rnetser — APPROVED** [review]

**Review by rnetser — APPROVED** [review]

**Comment by redhat-qe-bot1** [comment]
**Manual cherry-pick is needed**
Cherry pick failed for acdcfd5bf6ad15086db0396341ccb974456b1b24 to v4.15:
To cherry-pick run:
```
git remote update
git checkout v4.15
git pull origin v4.15
git checkout -b resources-definitions-tests-v4.15
git cherry-pick acdcfd5bf6ad15086db0396341ccb974456b1b24
git push origin resources-definitions-tests-v4.15
```

**Pull request merged**
