### PR TITLE
point main to kubernetes 1.30, since no wrapper branch points to it currently

### PR DESCRIPTION
**Pull request by dbasunag**
…urrently

## Summary by CodeRabbit

- **Chores**
	- Updated the version specification for the `kubernetes` dependency to allow for more flexible patch versions within the major version 30.

### CODE REVIEW

**Comment by msi-b1** [comment]
Report bugs in [Issues](https://github.com/myakove/github-webhook-server/issues)

The following are automatically added:
 * Add reviewers from OWNER file (in the root of the repository) under reviewers section.
 * Set PR size label.
 * New issue is created for the PR. (Closed when PR is merged/closed)
 * Run [pre-commit](https://pre-commit.ci/) if `.pre-commit-config.yaml` exists in the repo.

Available user actions:
 * To mark PR as WIP comment `/wip` to the PR, To remove it from the PR comment `/wip cancel` to the PR.
 * To block merging of PR comment `/hold`, To un-block merging of PR comment `/hold cancel`.
 * To mark PR as verified comment `/verified` to the PR, to un-verify comment `/verified cancel` to the PR.
        verified label removed on each new commit push.
 * To cherry pick a merged PR comment `/cherry-pick <target branch to cherry-pick to>` in the PR.
    * Multiple target branches can be cherry-picked, separated by spaces. (`/cherry-pick branch1 branch2`)
    * Cherry-pick will be started when PR is merged
 * To build and push container image command `/build-and-push-container` in the PR (tag will be the PR number).
    * You can add extra args to the Podman build command
        * Example: `/build-and-push-container --build-arg OPENSHIFT_PYTHON_WRAPPER_COMMIT=<commit_hash>`
 * To add a label by comment use `/<label name>`, to remove, use `/<label name> cancel`
 * To assign reviewers based on OWNERS file use `/assign-reviewers`
 * To check if PR can be merged use `/check-can-merge`

<details>
<summary>Supported /retest check runs</summary>

 * `/retest tox`: Retest tox
 * `/retest python-module-install`: Retest python-module-install

</details>

<details>
<summary>Supported labels</summary>

 * hold
 * verified
 * wip
 * lgtm

</details>

**Comment by myakove** [comment]
`main` should always point to the latest version.
/hold

**Comment by dbasunag** [comment]
> `main` should always point to the latest version. /hold

Currently no wrapper branch is aligned with kubernetes 30.*.*, OCP 4.17, and cnv 4.17 that are currently under test are based off kubernetes 1.30. OCP 4.18 would be based off 31.*.*. Unless a branch is cut for 4.17, test repositories would be forced to use newer kubernetes versions to consume newer code changes in main.
```
Because openshift-python-wrapper (0.0.0) @ file:///Users/dbasunag/repos/openshift-python-wrapper depends on kubernetes (^31.0.0)
 and cnv-tests-4-17 depends on kubernetes (30.*.*), openshift-python-wrapper is forbidden.
So, because cnv-tests-4-17 depends on openshift-python-wrapper (0.0.0) @ file:///Users/dbasunag/repos/openshift-python-wrapper, version solving failed.
```
Newer apis can negatively impact test repos.

**Pull request merged**
