### PR TITLE
adding Scheduled phase to vmi

### PR DESCRIPTION
**Pull request by Ahmad-Hafe**
Short description:
adding Scheduled phase to VMI

More details:
adding Scheduled phase to VMI because its missing, and need to test all phases for T2 tests

What this PR does / why we need it:
require to add Scheduled phase in order to test T2

Which issue(s) this PR fixes:
Fixing the needs to inheritance the Scheduled phase rather than hard code

Special notes for reviewer:
none

Bug:
none

### CODE REVIEW

**Comment by myakove** [comment]
/hold

base commit is old
```
* ba3910e5 - (HEAD, origin/pr/1645) adding Scheduled phase to vmi (2 hours ago) <Ahmad Hafe>
* f5002170 - WaitingForVolumeBinding VM status (#835) (1 year, 4 months ago) <Adolfo Aguirrezabal>

```

**Comment by redhat-qe-bot1** [comment]
Label 1645) is not a predefined one, will not be added / removed.
Available labels:

 * hold
 * verified
 * wip
 * lgtm

**Review by omrirh — APPROVED** [review]

**Review by rnetser — APPROVED** [review]

**Pull request merged**
