### PR TITLE
get_client - support kubeconfig dict

### PR DESCRIPTION
**Pull request by rnetser**

### CODE REVIEW

**Comment by rnetser** [comment]
!verified

**Review by myakove — DISMISSED** [review]

**Review by myakove — APPROVED** [review]

**Comment by rnetser** [comment]
!verified

**Comment by rnetser** [comment]
!verified

**Review by myakove — APPROVED** [review]

**Comment by myakove** [comment]
!verified

**Comment by myakove** [comment]
!cherry-pick v4.11

**Pull request merged**
