### PR TITLE
Update KubeDescheduler

### PR DESCRIPTION
**Pull request by sarahbx**
* Include 'mode'
* Correct management_state typo

### CODE REVIEW

**Comment by sarahbx** [comment]
!verified

**Review by myakove — APPROVED** [review]

**Comment by sarahbx** [comment]
!cherry-pick v4.11

**Comment by myakove** [comment]
!cherry-pick v4.11

**Comment by myakove** [comment]
!test-label

**Comment by myakove** [comment]
!verified

**Comment by myakove** [comment]
!-verified

**Comment by myakove** [comment]
!verified

**Comment by myakove** [comment]
!cherry-pick v4.11

**Comment by myakove** [comment]
!cherry-pick v4.11

**Pull request merged**
