### PR TITLE
Resource additions for standalone k8s-nmstate cherry-pick for v4.10

### PR DESCRIPTION
**Pull request by yossisegev**
1. NMState CR.
2. Add spec.updateStrategy.registryPoll.interval to CatalogSource.
(Needed for installing standalone k8s-nmstate).

### CODE REVIEW

**Review by myakove — APPROVED** [review]

**Review by rnetser — APPROVED** [review]

**Comment by rnetser** [comment]
@yossisegev can this PR be closed? https://github.com/RedHatQE/openshift-python-wrapper/pull/691 was merged

**Comment by yossisegev** [comment]
This PR is a backport for 4.10, so it should also be merged.

**Comment by rnetser** [comment]
@yossisegev The code is already in v4.10

**Comment by yossisegev** [comment]
Right, missed that, sorry.

**Pull request closed without merging**
