### PR TITLE
Raise ExecOnPodError on 'Failure' in pod.execute

### PR DESCRIPTION
**Pull request by jpeimer**
##### Short description:
Raise ExecOnPodError on 'Failure' in pod.execute

### CODE REVIEW

**Comment by jpeimer** [comment]
!verified

**Review by myakove — APPROVED** [review]

**Comment by myakove** [comment]
!cherry-pick v4.11

**Comment by myakove** [comment]
!cherry-pick v4.11

**Comment by myakove** [comment]
!cherry-pick v4.11

**Comment by myakove** [comment]
!cherry-pick v4.11

**Comment by myakove** [comment]
!cherry-pick v4.11

**Comment by jpeimer** [comment]
!cherry-pick v4.10

**Comment by jpeimer** [comment]
!cherry-pick v4.9

**Comment by jpeimer** [comment]
!cherry-pick v4.8

**Comment by jpeimer** [comment]
!cherry-pick v4.8

**Comment by jpeimer** [comment]
!cherry-pick v4.8

**Comment by jpeimer** [comment]
!cherry-pick v4.8

**Pull request merged**
