### PR TITLE
Fixed an issue with high-performance templates

### PR DESCRIPTION
**Pull request by obaireys**
The previous attribute name HIGH_PERFORMANCE caused an AttributeError.

### CODE REVIEW

**Comment by myakove** [comment]
HIGH_PERFORMANCE it's just the name of the arg, how come it fail something?

**Comment by obaireys** [comment]
> HIGH_PERFORMANCE it's just the name of the arg, how come it fail something?

The high-performance templates' label is `workload.template.kubevirt.io/highperformance`, so the workload attribute's value must be `highperformance`. On line 66 (in the function `generate_template_labels`) the uppercase of the workload name is assumed to be the attribute name, at which point its value is appended to the workload label. Thus, with the previous attribute name of `HIGH_PERFORMANCE`, an AttributeError is thrown any time the `highperformance` workload is used.

**Comment by rnetser** [comment]
Got it

/lgtm

**Comment by rnetser** [comment]
Note that you need to add a PR to fix any dependant tests code

**Comment by obaireys** [comment]
> Note that you need to add a PR to fix any dependant tests code

Noted, will do.

**Pull request merged**
