### PR TITLE
Pin timeout-sampler version

### PR DESCRIPTION
**Pull request by myakove**

### CODE REVIEW

**Comment by redhat-qe-bot1** [comment]
Cherry-pick requested for PR: `Pin timeout-sampler version` by user `myakove`
Adding label/s `cherry-pick-v4.15` for automatic cheery-pick once the PR is merged

**Review by rnetser — APPROVED** [review]

**Comment by redhat-qe-bot2** [comment]
**Manual cherry-pick is needed**
Cherry pick failed for e2a2be287c411ed49d1772441cb7333d108be083 to v4.14:
To cherry-pick run:
```
git remote update
git checkout v4.14
git pull origin v4.14
git checkout -b timeout-sampler-pin-version-v4.14
git cherry-pick e2a2be287c411ed49d1772441cb7333d108be083
git push origin timeout-sampler-pin-version-v4.14
```

**Comment by redhat-qe-bot2** [comment]
**Manual cherry-pick is needed**
Cherry pick failed for e2a2be287c411ed49d1772441cb7333d108be083 to v4.15:
To cherry-pick run:
```
git remote update
git checkout v4.15
git pull origin v4.15
git checkout -b timeout-sampler-pin-version-v4.15
git cherry-pick e2a2be287c411ed49d1772441cb7333d108be083
git push origin timeout-sampler-pin-version-v4.15
```

**Pull request merged**
