### PR TITLE
Run --update-schema against openshift 4.18, add kind ModelRegistry

### PR DESCRIPTION
**Pull request by lugi0**
## Summary by CodeRabbit

- **Chores**
	- Updated the version number from v1.31.0 to v1.31.2 in the version file.

### CODE REVIEW

**Review by rnetser — APPROVED** [review]

**Comment by rnetser** [comment]
please fix the tests

**Comment by myakove** [comment]
@lugi0 I pushed a PR that fixes the tests https://github.com/RedHatQE/openshift-python-wrapper/pull/2214
(cannot pushed to your PR since it's in your fork)

**Comment by lugi0** [comment]
@myakove thanks, that looks good to me, let me know if you want to merge yours and I can close this one

**Comment by lugi0** [comment]
@myakove I see that you merged your PR, I'm closing this one

**Pull request closed without merging**
