### PR TITLE
Add wait_for_resource parameter for Resource

### PR DESCRIPTION
**Pull request by lugi0**
##### Short description:
the `deploy`/`create` methods expect a `wait` parameter which would wait for the resource being deployed/created, but this is never passed down from `__init__` or `__enter__` and thus always defaults to `False`. Adding the parameter in these two functions allows us to use this while creating resources. 

##### More details:
Tested with Namespace creation
```
In [7]: ns = Namespace(name="my-test", wait_for_resource=True, client=client)

In [8]: ns
Out[8]: <ocp_resources.namespace.Namespace at 0x117f31190>

In [9]: ns.deploy()
2024-10-14T16:35:51.243289 ocp_resources Namespace INFO Create Namespace my-test
2024-10-14T16:35:51.243795 ocp_resources Namespace INFO Posting {'apiVersion': 'v1', 'kind': 'Namespace', 'metadata': {'name': 'my-test'}, 'spec': {}}
/Users/lgiorgi/Desktop/Work/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/Users/lgiorgi/Desktop/Work/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Out[9]: <ocp_resources.namespace.Namespace at 0x117f31190>

In [10]: ns.delete()
2024-10-14T16:36:34.376997 ocp_resources Namespace INFO Delete Namespace my-test
/Users/lgiorgi/Desktop/Work/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/Users/lgiorgi/Desktop/Work/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
2024-10-14T16:36:34.649673 ocp_resources Namespace INFO Deleting {'kind': 'Namespace', 'apiVersion': 'v1', 'metadata': {'name': 'my-test', 'uid': 'a6003107-f7b6-4b24-ac6a-aaf6d1b7b004', 'resourceVersion': '89029295', 'creationTimestamp': '2024-10-14T14:34:17Z', 'labels': {'kubernetes.io/metadata.name': 'my-test', 'pod-security.kubernetes.io/audit': 'restricted', 'pod-security.kubernetes.io/audit-version': 'v1.24', 'pod-security.kubernetes.io/warn': 'restricted', 'pod-security.kubernetes.io/warn-version': 'v1.24'}, 'annotations': {'openshift.io/sa.scc.mcs': 's0:c28,c7', 'openshift.io/sa.scc.supplemental-groups': '1000770000/10000', 'openshift.io/sa.scc.uid-range': '1000770000/10000'}, 'managedFields': [{'manager': 'pod-security-admission-label-synchronization-controller', 'operation': 'Apply', 'apiVersion': 'v1', 'time': '2024-10-14T14:35:24Z', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:labels': {'f:pod-security.kubernetes.io/audit': {}, 'f:pod-security.kubernetes.io/audit-version': {}, 'f:pod-security.kubernetes.io/warn': {}, 'f:pod-security.kubernetes.io/warn-version': {}}}}}, {'manager': 'OpenAPI-Generator', 'operation': 'Update', 'apiVersion': 'v1', 'time': '2024-10-14T14:34:17Z', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:labels': {'.': {}, 'f:kubernetes.io/metadata.name': {}}}}}, {'manager': 'cluster-policy-controller', 'operation': 'Update', 'apiVersion': 'v1', 'time': '2024-10-14T14:35:23Z', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:annotations': {'.': {}, 'f:openshift.io/sa.scc.mcs': {}, 'f:openshift.io/sa.scc.supplemental-groups': {}, 'f:openshift.io/sa.scc.uid-range': {}}}}}]}, 'spec': {'finalizers': ['kubernetes']}, 'status': {'phase': 'Active'}}
/Users/lgiorgi/Desktop/Work/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Out[10]: True

In [11]: ns2 = Namespace(name="my-test", client=client)

In [12]: ns2.deploy()
2024-10-14T16:39:38.362860 ocp_resources Namespace INFO Create Namespace my-test
2024-10-14T16:39:38.363149 ocp_resources Namespace INFO Posting {'apiVersion': 'v1', 'kind': 'Namespace', 'metadata': {'name': 'my-test'}, 'spec': {}}
/Users/lgiorgi/Desktop/Work/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/Users/lgiorgi/Desktop/Work/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Out[12]: <ocp_resources.namespace.Namespace at 0x117b71950>

In [13]: ns2.delete()
2024-10-14T17:33:51.088265 ocp_resources Namespace INFO Delete Namespace my-test
/Users/lgiorgi/Desktop/Work/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/Users/lgiorgi/Desktop/Work/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
2024-10-14T17:33:51.723735 ocp_resources Namespace INFO Deleting {'kind': 'Namespace', 'apiVersion': 'v1', 'metadata': {'name': 'my-test', 'uid': '0b8a3872-8492-4a70-b05c-cc298b2cc889', 'resourceVersion': '89032573', 'creationTimestamp': '2024-10-14T14:38:04Z', 'labels': {'kubernetes.io/metadata.name': 'my-test', 'pod-security.kubernetes.io/audit': 'restricted', 'pod-security.kubernetes.io/audit-version': 'v1.24', 'pod-security.kubernetes.io/warn': 'restricted', 'pod-security.kubernetes.io/warn-version': 'v1.24'}, 'annotations': {'openshift.io/sa.scc.mcs': 's0:c28,c22', 'openshift.io/sa.scc.supplemental-groups': '1000800000/10000', 'openshift.io/sa.scc.uid-range': '1000800000/10000'}, 'managedFields': [{'manager': 'pod-security-admission-label-synchronization-controller', 'operation': 'Apply', 'apiVersion': 'v1', 'time': '2024-10-14T14:39:11Z', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:labels': {'f:pod-security.kubernetes.io/audit': {}, 'f:pod-security.kubernetes.io/audit-version': {}, 'f:pod-security.kubernetes.io/warn': {}, 'f:pod-security.kubernetes.io/warn-version': {}}}}}, {'manager': 'OpenAPI-Generator', 'operation': 'Update', 'apiVersion': 'v1', 'time': '2024-10-14T14:38:04Z', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:labels': {'.': {}, 'f:kubernetes.io/metadata.name': {}}}}}, {'manager': 'cluster-policy-controller', 'operation': 'Update', 'apiVersion': 'v1', 'time': '2024-10-14T14:39:11Z', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:annotations': {'.': {}, 'f:openshift.io/sa.scc.mcs': {}, 'f:openshift.io/sa.scc.supplemental-groups': {}, 'f:openshift.io/sa.scc.uid-range': {}}}}}]}, 'spec': {'finalizers': ['kubernetes']}, 'status': {'phase': 'Active'}}
/Users/lgiorgi/Desktop/Work/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
Out[13]: True
```

## Summary by CodeRabbit

- **New Features**
	- Introduced a `wait_for_resource` parameter for more control over resource deployment and cleanup.
	- Enhanced `deploy` and `clean_up` methods to conditionally wait for resource creation and deletion based on user preference.

These changes provide users with improved flexibility during resource management operations.

### CODE REVIEW

**Comment by myakove** [comment]
https://github.com/RedHatQE/openshift-python-wrapper/pull/2168 should fix the failing `tox` check

**Review by myakove — APPROVED** [review]

**Review by rnetser — APPROVED** [review]

**Review by rnetser — APPROVED** [review]

**Comment by lugi0** [comment]
Retested with `with`, notice the missing `Wait until Namespace my-test is created` in the second call.

```
In [4]: with Namespace(name="my-test", wait_for_resource=True, client=client) as ns:
   ...:     ns.status
   ...: 
2024-10-15T13:54:34.859780 ocp_resources Namespace INFO Create Namespace my-test
2024-10-15T13:54:34.860087 ocp_resources Namespace INFO Posting {'apiVersion': 'v1', 'kind': 'Namespace', 'metadata': {'name': 'my-test'}, 'spec': {}}
/Users/lgiorgi/Desktop/Work/wrapper-fork/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/Users/lgiorgi/Desktop/Work/wrapper-fork/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
2024-10-15T13:54:35.455212 ocp_resources Namespace INFO Wait until Namespace my-test is created
2024-10-15T13:54:35.455817 timeout_sampler INFO Waiting for 240 seconds [0:04:00], retry every 1 seconds. (Function: ocp_resources.resource.wait.lambda: self.exists)
/Users/lgiorgi/Desktop/Work/wrapper-fork/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
2024-10-15T13:54:35.589861 timeout_sampler INFO Elapsed time: 0.00035381317138671875 [0:00:00.000354]
2024-10-15T13:54:35.590356 ocp_resources Namespace INFO Get Namespace my-test status
/Users/lgiorgi/Desktop/Work/wrapper-fork/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
2024-10-15T13:54:35.725957 ocp_resources Namespace INFO Delete Namespace my-test
/Users/lgiorgi/Desktop/Work/wrapper-fork/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/Users/lgiorgi/Desktop/Work/wrapper-fork/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
2024-10-15T13:54:36.004014 ocp_resources Namespace INFO Deleting {'kind': 'Namespace', 'apiVersion': 'v1', 'metadata': {'name': 'my-test', 'uid': 'b5abddc3-aa6a-40c0-8d51-5e71d9240fc7', 'resourceVersion': '90135924', 'creationTimestamp': '2024-10-15T11:52:59Z', 'labels': {'kubernetes.io/metadata.name': 'my-test', 'pod-security.kubernetes.io/audit': 'restricted', 'pod-security.kubernetes.io/audit-version': 'v1.24', 'pod-security.kubernetes.io/warn': 'restricted', 'pod-security.kubernetes.io/warn-version': 'v1.24'}, 'annotations': {'openshift.io/sa.scc.mcs': 's0:c27,c9', 'openshift.io/sa.scc.supplemental-groups': '1000720000/10000', 'openshift.io/sa.scc.uid-range': '1000720000/10000'}, 'managedFields': [{'manager': 'pod-security-admission-label-synchronization-controller', 'operation': 'Apply', 'apiVersion': 'v1', 'time': '2024-10-15T11:54:07Z', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:labels': {'f:pod-security.kubernetes.io/audit': {}, 'f:pod-security.kubernetes.io/audit-version': {}, 'f:pod-security.kubernetes.io/warn': {}, 'f:pod-security.kubernetes.io/warn-version': {}}}}}, {'manager': 'OpenAPI-Generator', 'operation': 'Update', 'apiVersion': 'v1', 'time': '2024-10-15T11:52:59Z', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:labels': {'.': {}, 'f:kubernetes.io/metadata.name': {}}}}}, {'manager': 'cluster-policy-controller', 'operation': 'Update', 'apiVersion': 'v1', 'time': '2024-10-15T11:54:07Z', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:annotations': {'.': {}, 'f:openshift.io/sa.scc.mcs': {}, 'f:openshift.io/sa.scc.supplemental-groups': {}, 'f:openshift.io/sa.scc.uid-range': {}}}}}]}, 'spec': {'finalizers': ['kubernetes']}, 'status': {'phase': 'Active'}}
/Users/lgiorgi/Desktop/Work/wrapper-fork/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
2024-10-15T13:54:36.145244 ocp_resources Namespace INFO Wait until Namespace my-test is deleted
2024-10-15T13:54:36.145739 timeout_sampler INFO Waiting for 240 seconds [0:04:00], retry every 1 seconds. (Function: ocp_resources.resource.wait_deleted.lambda: self.exists)
/Users/lgiorgi/Desktop/Work/wrapper-fork/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/Users/lgiorgi/Desktop/Work/wrapper-fork/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/Users/lgiorgi/Desktop/Work/wrapper-fork/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/Users/lgiorgi/Desktop/Work/wrapper-fork/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/Users/lgiorgi/Desktop/Work/wrapper-fork/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/Users/lgiorgi/Desktop/Work/wrapper-fork/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/Users/lgiorgi/Desktop/Work/wrapper-fork/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
2024-10-15T13:54:43.130970 timeout_sampler INFO Elapsed time: 6.844934940338135 [0:00:06.844935]

In [5]: with Namespace(name="my-test", client=client) as ns:
   ...:     ns.status
   ...: 
2024-10-15T13:55:05.586577 ocp_resources Namespace INFO Create Namespace my-test
2024-10-15T13:55:05.586872 ocp_resources Namespace INFO Posting {'apiVersion': 'v1', 'kind': 'Namespace', 'metadata': {'name': 'my-test'}, 'spec': {}}
/Users/lgiorgi/Desktop/Work/wrapper-fork/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/Users/lgiorgi/Desktop/Work/wrapper-fork/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
2024-10-15T13:55:05.866016 ocp_resources Namespace INFO Get Namespace my-test status
/Users/lgiorgi/Desktop/Work/wrapper-fork/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
2024-10-15T13:55:06.004739 ocp_resources Namespace INFO Delete Namespace my-test
/Users/lgiorgi/Desktop/Work/wrapper-fork/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/Users/lgiorgi/Desktop/Work/wrapper-fork/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
2024-10-15T13:55:06.272846 ocp_resources Namespace INFO Deleting {'kind': 'Namespace', 'apiVersion': 'v1', 'metadata': {'name': 'my-test', 'uid': '8d90975d-e973-4e7b-8582-5d6b563601d9', 'resourceVersion': '90136413', 'creationTimestamp': '2024-10-15T11:53:30Z', 'labels': {'kubernetes.io/metadata.name': 'my-test', 'pod-security.kubernetes.io/audit': 'restricted', 'pod-security.kubernetes.io/audit-version': 'v1.24', 'pod-security.kubernetes.io/warn': 'restricted', 'pod-security.kubernetes.io/warn-version': 'v1.24'}, 'annotations': {'openshift.io/sa.scc.mcs': 's0:c27,c19', 'openshift.io/sa.scc.supplemental-groups': '1000740000/10000', 'openshift.io/sa.scc.uid-range': '1000740000/10000'}, 'managedFields': [{'manager': 'pod-security-admission-label-synchronization-controller', 'operation': 'Apply', 'apiVersion': 'v1', 'time': '2024-10-15T11:54:37Z', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:labels': {'f:pod-security.kubernetes.io/audit': {}, 'f:pod-security.kubernetes.io/audit-version': {}, 'f:pod-security.kubernetes.io/warn': {}, 'f:pod-security.kubernetes.io/warn-version': {}}}}}, {'manager': 'OpenAPI-Generator', 'operation': 'Update', 'apiVersion': 'v1', 'time': '2024-10-15T11:53:30Z', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:labels': {'.': {}, 'f:kubernetes.io/metadata.name': {}}}}}, {'manager': 'cluster-policy-controller', 'operation': 'Update', 'apiVersion': 'v1', 'time': '2024-10-15T11:54:37Z', 'fieldsType': 'FieldsV1', 'fieldsV1': {'f:metadata': {'f:annotations': {'.': {}, 'f:openshift.io/sa.scc.mcs': {}, 'f:openshift.io/sa.scc.supplemental-groups': {}, 'f:openshift.io/sa.scc.uid-range': {}}}}}]}, 'spec': {'finalizers': ['kubernetes']}, 'status': {'phase': 'Active'}}
/Users/lgiorgi/Desktop/Work/wrapper-fork/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
2024-10-15T13:55:06.416166 ocp_resources Namespace INFO Wait until Namespace my-test is deleted
2024-10-15T13:55:06.416645 timeout_sampler INFO Waiting for 240 seconds [0:04:00], retry every 1 seconds. (Function: ocp_resources.resource.wait_deleted.lambda: self.exists)
/Users/lgiorgi/Desktop/Work/wrapper-fork/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/Users/lgiorgi/Desktop/Work/wrapper-fork/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/Users/lgiorgi/Desktop/Work/wrapper-fork/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/Users/lgiorgi/Desktop/Work/wrapper-fork/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/Users/lgiorgi/Desktop/Work/wrapper-fork/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/Users/lgiorgi/Desktop/Work/wrapper-fork/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
/Users/lgiorgi/Desktop/Work/wrapper-fork/openshift-python-wrapper/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ods-qe-psi-04.osp.rh-ods.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
2024-10-15T13:55:13.390199 timeout_sampler INFO Elapsed time: 6.838379144668579 [0:00:06.838379]
```

**Pull request merged**
