### PR TITLE
Move kube_v1_api init to pod.execute

### PR DESCRIPTION
**Pull request by sarahbx**
##### Short description:
Reducing the number of attributes that must be handled
to serialize resources

### CODE REVIEW

**Comment by sarahbx** [comment]
verified

**Comment by sarahbx** [comment]
!verified

**Review by rnetser — COMMENTED** [review]
why is this change needed? this is a breaking change.

**Comment by myakove** [comment]
> why is this change needed? this is a breaking change.

it's not breaking change, but I would like to know the reason for this change.

(should be in the commit-msg)

**Comment by sarahbx** [comment]
!verified

**Review by myakove — APPROVED** [review]

**Comment by sarahbx** [comment]
!verified

**Review by myakove — APPROVED** [review]

**Comment by sarahbx** [comment]
!verified

**Pull request merged**
