### PR TITLE
Add "ImagePullBackOff" and "ErrImagePull" pod statuses

### PR DESCRIPTION
**Pull request by OhadRevah**

### CODE REVIEW

**Comment by OhadRevah** [comment]
@rnetser please let me know if the current description is OK

**Comment by rnetser** [comment]
@OhadRevah The PR's title should be updated as well

**Comment by OhadRevah** [comment]
Updated the title, please let me know if the current title is ok

**Review by rnetser — CHANGES_REQUESTED** [review]
Should be something like:
```
Add "ImagePullBackOff" and "ErrImagePull" pod statuses
```

**Comment by OhadRevah** [comment]
Updated the title

**Review by myakove — APPROVED** [review]

**Review by rnetser — APPROVED** [review]

**Comment by OhadRevah** [comment]
!verified

**Comment by OhadRevah** [comment]
!cherry-pick v4.11

**Pull request merged**
