### PR TITLE
Remove timeout sampler tests

### PR DESCRIPTION
**Pull request by myakove**
* Remove timeout sampler tests
* Remove pre-commit from tox

### CODE REVIEW

**Review by rnetser — CHANGES_REQUESTED** [review]
we should also remove https://github.com/RedHatQE/openshift-python-wrapper/blob/main/tests/unittests/test_utils.py

**Comment by myakove** [comment]
@rnetser I removed `unittests` folder completely

**Review by rnetser — APPROVED** [review]

**Pull request merged**
