### PR TITLE
Adding hypervisor connection uri based on the socket present in virt-launcher pod (#1096)

### PR DESCRIPTION
**Pull request by akri3i**
Signed-off-by: akriti gupta <akrgupta@redhat.com>

##### Short description:
Backporting for upgrade scenario
##### What this PR does / why we need it:
This PR update Virt Launcher Pod Hypervisor Connection URI based on the socket present in the pod 
https://github.com/kubevirt/kubevirt/pull/8619

##### Release note:

> virt-launcher: use `virtqemud` daemon instead of `libvirtd` if machine type is rhel9

### CODE REVIEW

**Comment by akri3i** [comment]
!verified

**Comment by myakove** [comment]
This is target to 4.12, Is this needed in 4.12?

**Comment by myakove** [comment]
> > Collaborator
> 
> yes

Your PR title have `in 4.13`

**Comment by akri3i** [comment]
> > > Collaborator
> > 
> > 
> > yes
> 
> Your PR title have `in 4.13`

As for upgrade from 4.12 to 4.13 , we use cnv-4.12 branch, we need it in v4.12 branch as well

**Comment by myakove** [comment]
> > > > Collaborator
> > > 
> > > 
> > > yes
> > 
> > 
> > Your PR title have `in 4.13`
> 
> As for upgrade from 4.12 to 4.13 , we use cnv-4.12 branch, we need it in v4.12 branch as well

This repo is not related or depend on any other repo or tests
If this is not existing in ocp 4.12 this shouldn't be cherry-pick to v4.12 branch.

**Review by myakove — APPROVED** [review]

**Pull request merged**
