### PR TITLE
Do not call `_get_port_from_nns` if no self.nodes

### PR DESCRIPTION
**Pull request by myakove**

### CODE REVIEW

**Review by rnetser — APPROVED** [review]

**Comment by myakove** [comment]
!verified

**Comment by myakove** [comment]
!verified

**Comment by myakove** [comment]
!verified

**Comment by sarahbx** [comment]
lgtm

**Review by rnetser — DISMISSED** [review]

**Comment by myakove** [comment]
!verified

**Review by rnetser — APPROVED** [review]

**Comment by myakove** [comment]
!verified

**Pull request merged**
