### PR TITLE
removing matchlabels field from migration policy 

### PR DESCRIPTION
**Pull request by akri3i**
Signed-off-by: akriti gupta <akrgupta@redhat.com>

##### What this PR does / why we need it:
Removes matchLabels field from specs of migration policy
##### Bug:
**Release note**:
None

### CODE REVIEW

**Comment by myakove** [comment]
PR https://github.com/kubevirt/kubevirt/pull/7322 is not merged
this need to be change here only after the code get downstream.

!DO-NOT-MERGE

**Comment by akri3i** [comment]
> PR [kubevirt/kubevirt#7322](https://github.com/kubevirt/kubevirt/pull/7322) is not merged this need to be change here only after the code get downstream.
> 
> !DO-NOT-MERGE



> PR [kubevirt/kubevirt#7322](https://github.com/kubevirt/kubevirt/pull/7322) is not merged this need to be change here only after the code get downstream.
> 
> !DO-NOT-MERGE

Hi, 
The PR that dropped matchlabels from migration policy is [https://github.com/kubevirt/kubevirt/pull/7510](https://github.com/kubevirt/kubevirt/pull/7510) , which is already merged
And i talked to dev they are not planning on merging [kubevirt/kubevirt#7322](https://github.com/kubevirt/kubevirt/pull/7322) anytime soon

**Comment by myakove** [comment]
@akri3i is https://github.com/kubevirt/kubevirt/pull/7510 already in any d/s ?

**Comment by akri3i** [comment]
> 

yes
From the latest 4.12-487 using upstream commit  https://github.com/kubevirt/kubevirt/commits/dd54314cfd1d7c410f48278769e774456ab3b8f4
we see the patch in d/s [https://github.com/kubevirt/kubevirt/commits/dd54314cfd1d7c410f48278769e774456ab3b[…]ab3b8f4&qualified_name=dd54314cfd1d7c410f48278769e774456ab3b8f4](https://github.com/kubevirt/kubevirt/commits/dd54314cfd1d7c410f48278769e774456ab3b8f4?before=dd54314cfd1d7c410f48278769e774456ab3b8f4+910&branch=dd54314cfd1d7c410f48278769e774456ab3b8f4&qualified_name=dd54314cfd1d7c410f48278769e774456ab3b8f4)

**Review by myakove — APPROVED** [review]

**Comment by akri3i** [comment]
!cherry-pick v4.12

**Pull request merged**
