### PR TITLE
Add Datasource bootsource property (#1601)

### PR DESCRIPTION
**Pull request by hmeir**
* Add snapshot property to Datasource class

* Add deprecation warning for DataSource pvc property

### CODE REVIEW

**Comment by redhat-qe-bot1** [comment]
Report bugs in [Issues](https://github.com/myakove/github-webhook-server/issues)

The following are automatically added:
 * Add reviewers from OWNER file (in the root of the repository) under reviewers section.
 * Set PR size label.
 * New issue is created for the PR. (Closed when PR is merged/closed)
 * Run [pre-commit](https://pre-commit.ci/) if `.pre-commit-config.yaml` exists in the repo.

Available user actions:
 * To mark PR as WIP comment `/wip` to the PR, To remove it from the PR comment `/wip cancel` to the PR.
 * To block merging of PR comment `/hold`, To un-block merging of PR comment `/hold cancel`.
 * To mark PR as verified comment `/verified` to the PR, to un-verify comment `/verified cancel` to the PR.
        verified label removed on each new commit push.
 * To cherry pick a merged PR comment `/cherry-pick <target branch to cherry-pick to>` in the PR.
    * Multiple target branches can be cherry-picked, separated by spaces. (`/cherry-pick branch1 branch2`)
    * Cherry-pick will be started when PR is merged
 * To build and push container image command `/build-and-push-container` in the PR (tag will be the PR number).
 * To add a label by comment use `/<label name>`, to remove, use `/<label name> cancel`

<details>
<summary>Supported /retest check runs</summary>

 * `/retest tox`: Retest tox
 * `/retest python-module-install`: Retest python-module-install

</details>

<details>
<summary>Supported labels</summary>

 * hold
 * verified
 * wip
 * lgtm

</details>

**Review by myakove — APPROVED** [review]

**Review by rnetser — APPROVED** [review]

**Comment by redhat-qe-bot1** [comment]
**Manual cherry-pick is needed**
Cherry pick failed for e78f80da7ead4660da95ada6752b35883336fa39 to v4.14:
To cherry-pick run:
```
git remote update
git checkout v4.14
git pull origin v4.14
git checkout -b datasource-snapshot-prop-v4.15-v4.14
git cherry-pick e78f80da7ead4660da95ada6752b35883336fa39
git push origin datasource-snapshot-prop-v4.15-v4.14
```

**Pull request merged**
