### PR TITLE
introduce autoflake

### PR DESCRIPTION
**Pull request by ibesso-rh**
##### Short description:
introduce autoflake pre-commit hook.

##### More details:
followed this reference to integrate via pre-commit:
https://github.com/myint/autoflake/pull/62

##### What this PR does / why we need it:
autoflake complements flake8 for removing unused imports
because flake8 just reports them and fails the pre-commit

##### Special notes for reviewer:

Note that applying pre-commit on all files causes the following code to be modified:

class ValueMismatch(Exception):
    """
    Raises when value doesn't match the class value
    """

    pass

the "pass" is redundant, and therefore, removed.

It's fine by me, but on another repo where I introduced autoflake that applied the same modification, you did not want this to be modified, so eventually that "pass" was replaced by actual effective code.

What do you want me to do?
1. leave it as is (default, my choice too).
2. remove this class?
3. add code to this class definition?
4. wait for you to add code to this class definition?

##### Release notes:

```
introduce autoflake pre-commit hook
```

### CODE REVIEW

**Comment by myakove** [comment]
@ibesso-rh if pass is redundant, keep it out
Fix CI errors, please.

**Comment by myakove** [comment]
@ibesso-rh Please add `None` in the `Release notes:` section.

**Comment by ibesso-rh** [comment]
> @ibesso-rh if `pass` is redundant, keep it out
> Fix CI errors, please.

fixed. I ran pre-commit with autoflake included.

**Comment by ibesso-rh** [comment]
> @ibesso-rh Please add `None` in the `Release notes:` section.

done

**Pull request merged**
