### PR TITLE
add ForbiddenError to the retry list and add default exceptions to a few calls

### PR DESCRIPTION
**Pull request by dbasunag**
##### More details:
add DEFAULT_CLUSTER_RETRY_EXCEPTIONS to the following calls:

1. wait
2. wait_for_status
3. wait_for_ready_status

### CODE REVIEW

**Review by rnetser — APPROVED** [review]

**Comment by dbasunag** [comment]
!verified

**Review by myakove — APPROVED** [review]

**Comment by myakove** [comment]
!lgtm

**Comment by dbasunag** [comment]
!cherry-pick v4.12

**Comment by rnetser** [comment]
!verified

**Comment by dbasunag** [comment]
!cherry-pick v4.11

**Pull request merged**
