### PR TITLE
Node Health Check was incorrectly mentioned as namespace dependent in  documentation.

### PR DESCRIPTION
**Pull request by geetikakay**
Signed-off-by: Geetika Kapoor <gkapoor@redhat.com>

##### Short description:

This PR is to fix node health check and removing it's dependency from namespace. There is a documentation bug to fix it  from openshift documentation. 

Refer : https://issues.redhat.com/browse/TELCODOCS-1029

##### What this PR does / why we need it:
When node health check operator is installed it installs Nodehealthcheck and self-node-remediation. Out of which nodehealthcheck is cluster scoped and self-node-remediation is namespaced scope but documentation mentioned both as namespaced scope.

### CODE REVIEW

**Review by rnetser — APPROVED** [review]

**Comment by geetikakay** [comment]
!verified

**Review by myakove — APPROVED** [review]

**Comment by geetikakay** [comment]
!verified

**Comment by myakove** [comment]
!verified (rebase only)

**Comment by myakove** [comment]
!verified

**Pull request merged**
