### PR TITLE
Fix a mix between spec.netAttachDefName and spec.name fields

### PR DESCRIPTION
**Pull request by Anatw**

### CODE REVIEW

**Review by myakove — COMMENTED** [review]
This means that after your last PR this was broken? 
If so, how did you verify your last PR?

**Comment by Anatw** [comment]
> This means that after your last PR this was broken? If so, how did you verify your last PR?

I verified it by running an entire module creating such resources. I am not sure how this happened,  I might have accidentally ran it against master and not the PR.

**Review by segevyos — COMMENTED** [review]
/lgtm

**Comment by myakove** [comment]
your original PR we reverted.

**Comment by segevyos** [comment]
> your original PR we reverted.

@myakove The [original PR](https://github.com/RedHatQE/openshift-python-wrapper/pull/1697) also included VLAN and MTU, so reverting it also removes the support of these parameters.

**Comment by myakove** [comment]
The original PR breaks the code, therefore needs to be reverted

**Pull request closed without merging**
