### PR TITLE
Add CSIDriver Resource [4.9 cherry-pick of #522]

### PR DESCRIPTION
**Pull request by jpeimer**
##### Short description:
Add CSIDriver Resource

### CODE REVIEW

**Review by rnetser — APPROVED** [review]
@jpeimer, please create a PR in main to rename the module; should be `csi_driver.py``

**Comment by myakove** [comment]
> @jpeimer, please create a PR in main to rename the module; should be `csi_driver.py``

can be renamed in main and cherry-picked to all branches after this is one in merged

**Comment by myakove** [comment]
@jpeimer please close this PR

**Comment by jpeimer** [comment]
Closing this PR, will rename to `csi_driver.py` in main and cherry-pick. 
Thanks @myakove and @rnetser

**Pull request closed without merging**
