### PR TITLE
WaitingForVolumeBinding VM status

### PR DESCRIPTION
**Pull request by aaguirreRH**
##### Short description:
Adds the WaitingForVolumeBinding status to the VirtualMachine resource

### CODE REVIEW

**Review by myakove — APPROVED** [review]

**Comment by aaguirreRH** [comment]
!verified

**Comment by aaguirreRH** [comment]
!cherry-pick v4.12

**Comment by jpeimer** [comment]
!cherry-pick v4.10

**Comment by dshchedr** [comment]
!cherry-pick v4.9

**Pull request merged**
