### PR TITLE
remove FLAVOR_KUBEVIRT_IO

### PR DESCRIPTION
**Pull request by dbasunag**

### CODE REVIEW

**Review by rnetser — APPROVED** [review]

**Comment by geetikakay** [comment]
looks good.

**Comment by dbasunag** [comment]
!verified

**Review by myakove — APPROVED** [review]

**Comment by myakove** [comment]
!cherry-pick v4.12

**Comment by myakove** [comment]
!cherry-pick v4.12

**Comment by myakove** [comment]
!cherry-pick v4.12

**Comment by myakove** [comment]
!cherry-pick v4.12

**Comment by myakove** [comment]
!cherry-pick v4.12

**Pull request merged**
