### PR TITLE
Removing matchLabels from vmi_selector

### PR DESCRIPTION
**Pull request by akri3i**
Signed-off-by: akriti gupta <akrgupta@redhat.com>

##### Short description:
Following PR https://github.com/kubevirt/kubevirt/pull/7510 suggests matchLabels is now gone from MigrationPolicy spec, thus removing the matchLabels field from vmi_selector while creating migtation Policy
##### What this PR does / why we need it:
Removes matchLabels field from vmi_selector while creating Migration Policy
##### Special notes for reviewer:
#####Release note:
None

### CODE REVIEW

**Comment by akri3i** [comment]
!verified

**Comment by myakove** [comment]
Can you please add a reference in the PR why this remove needed.

**Comment by akri3i** [comment]
> 
Following PR https://github.com/kubevirt/kubevirt/pull/7510 suggests matchLabels is now gone from MigrationPolicy spec, thus removing the matchLabels field from vmi_selector while creating migtation Policy

**Comment by akri3i** [comment]
> Can you please add a reference in the PR why this remove needed.



> Can you please add a reference in the PR why this remove needed.

Following PR https://github.com/kubevirt/kubevirt/pull/7510 suggests matchLabels is now gone from MigrationPolicy spec, thus removing the matchLabels field from vmi_selector while creating migtation Policy

**Review by rnetser — APPROVED** [review]

**Comment by akri3i** [comment]
!verified

**Comment by myakove** [comment]
!cherry-pick v4.12

**Pull request merged**
