### PR TITLE
Added resource scheduler. This is a cluster wide resource.

### PR DESCRIPTION
**Pull request by geetikakay**
Signed-off-by: Geetika Kapoor <gkapoor@redhat.com>

##### Short description:
Schedulers are Cluster scoped resource . 

KIND:     Scheduler
VERSION:  config.openshift.io/v1
##### What this PR does / why we need it:
This can be used to find out if master are Schedulable.

For 6 node-cluster - mastersSchedulable: false
For 3 node-cluster - mastersSchedulable: true

### CODE REVIEW

**Review by rnetser — APPROVED** [review]

**Comment by geetikakay** [comment]
!verified

**Review by myakove — APPROVED** [review]

**Comment by geetikakay** [comment]
!verified

**Comment by myakove** [comment]
!verified

**Comment by myakove** [comment]
!verified

**Pull request merged**
